#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    fsp_err_t err = FSP_SUCCESS;
    /* Initializes the module. */
    err = R_GPT_Open(&g_timer3_ctrl, &g_timer3_cfg);
    /* Handle any errors. This function should be defined by the user. */
    assert(FSP_SUCCESS == err);

    /* Start the timer. */
    (void) R_GPT_Start(&g_timer3_ctrl);

    err = R_GPT_PeriodSet(&g_timer3_ctrl, 9000);//频率
    assert(FSP_SUCCESS == err);
    R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);//不加延时可能会设置不成功


    err = R_GPT_DutyCycleSet(&g_timer3_ctrl, 2250, GPT_IO_PIN_GTIOCA);//占空比
    assert(FSP_SUCCESS == err);
    R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);//不加延时可能会设置不成功


//    err = R_GPT_Close(&g_timer3_ctrl);
//    assert(FSP_SUCCESS == err);
//    R_BSP_SoftwareDelay (20, BSP_DELAY_UNITS_MILLISECONDS);

    /* -----------------------------------------
     * PWM “呼吸”效果核心循环
     * duty   : 0‑1000，对应 0 %‑100 % 占空比（后面 ×9 映射到 GPT 计数）
     * rising : true 表示占空比递增，false 表示递减
     * -----------------------------------------*/
    int  duty   = 1;      /* 当前占空比计数（1/1000 分辨率）          */
    bool rising = true;   /* true=递增，false=递减                     */
    while(1)
    {
        /* ---------- 1. 计算下一步 duty ---------- */
        if (rising)                       /* 处于递增阶段 */
        {
            duty++;                       /* 占空比 +1    */
            if (duty >= 1000)             /* 到达上限时   */
            {
                duty   = 1000;            /* 饱和         */
                rising = false;           /* 方向改为递减 */
            }
        }
        else                              /* 递减阶段 */
        {
            duty--;                       /* 占空比 −1    */
            if (duty <= 0)                /* 到达下限时   */
            {
                duty   = 0;               /* 饱和         */
                rising = true;            /* 方向改为递增 */
            }
        }

        /* ---------- 2. 将新 duty 写入 GPT ---------- */
        /* 9 × duty 把 0‑1000 映射到 0‑9000 的 GPT 计数值，
           具体比例由 PWM 频率 / 时钟设置决定。               */
        err = R_GPT_DutyCycleSet(&g_timer3_ctrl,
                                 9 * duty,
                                 GPT_IO_PIN_GTIOCA);
        assert(FSP_SUCCESS == err);       /* 确认写入成功 */

        /* ---------- 3. 节拍延时 ---------- */
        /* 1 ms 更新一次占空比，控制呼吸速度。
           若运行在 RTOS，可改为 vTaskDelay(1).              */
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
